server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service}
    username: ${DB_USERNAME:user_service}
    password: ${DB_PASSWORD:user_service}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  public-key-location: ${JWT_PUBLIC_KEY_LOCATION:classpath:keys/public_key.pem}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
