apiVersion: v2
name: task-service
description: task-service Helm chart
type: application
version: 0.1.0
appVersion: "0.1.0-SNAPSHOT"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
