apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ required "secrets.dbUsername gereklidir (--set secrets.dbUsername=...)" .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ required "secrets.dbPassword gereklidir (--set secrets.dbPassword=...)" .Values.secrets.dbPassword | quote }}
