apiVersion: v2
name: observability
description: >-
  Local geliştirme için gözlemlenebilirlik yığını: Prometheus (metrikler), Grafana
  (dashboard), Tempo (dağıtık tracing), Loki+Promtail (log toplama).
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: 29.19.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: 10.5.15
    repository: "https://grafana.github.io/helm-charts"
  - name: tempo
    version: 1.24.4
    repository: "https://grafana.github.io/helm-charts"
  - name: loki-stack
    version: 2.10.3
    repository: "https://grafana.github.io/helm-charts"
