apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtKeys.secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  private_key.pem: {{ required "jwtKeys.privateKey gereklidir (--set-file jwtKeys.privateKey=...)" .Values.jwtKeys.privateKey | quote }}
  public_key.pem: {{ required "jwtKeys.publicKey gereklidir (--set-file jwtKeys.publicKey=...)" .Values.jwtKeys.publicKey | quote }}
