{{- if .Values.postgres.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.backup.storageSize }}
{{- end }}
